/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.yourcompany.struts.form.LoginForm;

/** 
 * MyEclipse Struts
 * Creation date: 09-20-2021
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="loginForm" input="/login.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/success.jsp"
 * @struts.action-forward name="failure" path="/login.jsp"
 */
public class LoginAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute( 
		     ActionMapping mapping, 
		     ActionForm form, 
		     HttpServletRequest request, 
		     HttpServletResponse response) { 
		        LoginForm userLoginForm = (LoginForm)form;
		            if(userLoginForm.getUsername().equals("testing")
		             &&
		             userLoginForm.getPassword().equals("testing1")) 
		               { 
		                request.setAttribute("userName",
		                userLoginForm.getUsername()); 
		                return
		                mapping.findForward("success"); 
		               }         
		 
		               return mapping.findForward("failure"); 
		              }
}